discord:
  webhooks: # ссылки вебхуков разных уровней доступа
    url_lvl1: "https://discordapp.com/api/webhooks/523289724639510548/cEkuF1hXAqH5KjCIHIpNUS2oNc-wvDgBjA7S2TETZt9Xu9uF5U8wKuHInx2vHYQmIOTJ"
    url_lvl2: "https://discordapp.com/api/webhooks/523488651330453564/Yes5EtngU8HmBnUoQKS3DZVWdghfd58cf3LD8w_WeWLxuQo3U91PZaKtEbEfNO-YVRiF"

    player_avatar_url: "https://allformine.ru/banava?name=" # ссылка на API для получения ссылки на аватар
  logger:
    ignoredCommands: # данные команды не будут отправлены в дискорд.
    - "/l"
    - "/t"
    - "/g"
    - "/msg"
    - "/r"
    - "/pm"
    - "/st"
    triggerWords: # если в сообщении человека будут обнаружены следующие слова, то об этом отправится предупреждение в дискорд.
    - "дюп"
    - "краш"
    - "баг"
    - "чит"
tps:
  alarm_if_less: 14 # Если TPS ниже, чем данное число, то в дискорд отправится сообщение.
  bad_tps_count: 100 # Уведомление в дискорд отправится только в том случае, если количество TPS ниже нормы продержится данное количество тиков.
vips: # VIP-привелегии.
  alpha: # PEX-группа привелегии, которая будет выдана игроку при покупке через плагин VipZero
    cost: 1990 # цена в токенах
  beta:
    cost: 4990
  gamma:
    cost: 7990
balanceapi:
  url: "https://allformine.ru/balanceapi"
protocol: # Все, что связано с ServerListPing и LegacyPing
  motd: # Плагин меняет MOTD сервера.
    firstLine: "Здесь могла бы быть ваша реклама"
    secondLine: "Но её не будет, иди нахуй"
  hide_vanished: # Скрывать игроков в ванише из..
    serverListPing: true
    legacyPing: true
loader_groups: # чтобы настроить игроку или группе прогрузку чанков, надо выдать ему permission
  alpha:       # типа afmcp.loader.<группа>
    count: 1 # лимит прогрузчиков
    loadAfterLogoutTime: -1 # сколько нужно грузить чанк после выхода игрока из игры в секундах.
  beta:                     # если не нужно грузить после выхода, необходимо поставить -1
    count: 2
    loadAfterLogoutTime: 3600
  gamma:
    count: 3
    loadAfterLogoutTime: 10800
server_maintenance:
  enabled: false
  kickMessage: "&cВ данным момент сервер на технических работах.\n&fВы можете узнать о них больше в группе ВК, Discord или сайте сервера."
server_api: # API для бота Discord - HTTP сервер.
  enabled: true # Включить/выключить HTTP сервер.
  port: 4049
playerdata: # НЕ МЕНЯТЬ. Внутренняя инфа плагина
loaders: # Здесь записаны прогрузчики.
ambient_data:
rgname_data:
networkwatcher: false
